[package]

name = "json_macros"
version = "0.0.5"
authors = ["Tom Jakubowski <tom@crystae.net>"]

readme = "README.markdown"
license = "MIT"
repository = "https://github.com/tomjakubowski/json_macros"
description = """
Convenience macros for constructing JSON objects from literals.
"""
keywords = ["json", "macros", "plugins"]

[lib]

name = "json_macros"
path = "src/macro.rs"
plugin = true

[[test]]
name = "tests"

[[example]]
name = "kitchen-sink"
path = "examples/kitchen_sink.rs"
